FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY auth/target/TestRegister1-0.0.1-SNAPSHOT.jar app.jar
RUN mkdir -p uploads
EXPOSE 8080
VOLUME ["/app/uploads"]
ENTRYPOINT ["java", "-jar", "app.jar", "--spring.profiles.active=prod"]
