FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY backend/app.jar app.jar
RUN mkdir -p uploads
EXPOSE 8080
VOLUME ["/app/uploads"]
ENTRYPOINT ["java", "-jar", "app.jar", "--spring.profiles.active=prod"]
